from . import admission_candidate
from . import admission_candidate_stage
from . import admission_form_template
from . import admission_form_mapping
from . import admission_mapping_line
from . import admission_import_batch
from . import limesurvey_server_config
from . import ir_attachment
from . import admission_dashboard